### ISSUE TITLE
Stickers not displaying as images

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#17]
Links show as 'MYSERVERDOMAIN:9003/document/id' but with no file type appended to the end.
In Firefox 57 I get 'The Image can't be displayed because it contains errors', and it tries to parse it as a JPEG.

**Comment by vanya-klimenko** [comment]
Bump.

Same for videos etc.

**Comment by MaskRay** [comment]
Fixed in 3c5c29b

```
Content-Length:155904
Content-Type:video/mp4
Date:Sun, 28 Jan 2018 01:40:45 GMT
Server:Python/3.6 aiohttp/2.3.9
```

**Comment by rodneyrod** [comment]
Did a git pull and also refreshed the requirements.txt but I'm still getting the same error in Firefox with stickers, still can't get them to display.

**Comment by MaskRay** [comment]
```python
            with open(filename, 'rb') as f:
                mime = None
                if sys.platform == 'linux':
                    try:
                        mime = subprocess.check_output(['xdg-mime', 'query', 'filetype', filename],
                                                       stdin=subprocess.DEVNULL).decode().strip()
                    except:
                        pass
                if mime is None:
                    mime = mimetypes.guess_type(filename)[0]
                return aiohttp.web.Response(body=f.read(), headers={'Content-Type': mime})
```

`xdg-mime query filetype $filename` is used to detect Content-Type. But it is unavailable on Mac OS X or Windows

**Comment by rodneyrod** [comment]
@MaskRay I see, is there any way to do this server side on Linux? Or failing that, is there a workaround that's cross platform across clients?
